### ISSUE TITLE
PRIORITY: See That Regions of BC Are Not Being Forgotten

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#60] opened 2022-04-24 23:37 UTC
**As a [description of user]?**
member of the general public in BC,	

**I want to [functionality]**
see plans and policies for specific regions of BC,

**So that [benefit]**
see what's relevant to me and also feel confident that other regions are not being forgotten.

**Additional context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
Agreed-upon confirmation of the requirements when done can be deemed as complete

**Comment by apuns** [comment] 2022-04-25 19:07
Closed, was a duplicate of issue #58

**Closed** 2022-04-25 19:06 UTC
Labels: CleanBC
