### ISSUE TITLE
Taxpayers Giving Feedback to MLAs

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#72] opened 2022-04-25 00:14 UTC
**As a [description of user]?**
taxpayer in BC,	

**I want to [functionality]**
access information that helps me understand how BC's plans for zero emissions impacts me as a consumer (ie. increase in taxes...)

**So that [benefit]**
know how it impacts me/give feedback to my MLA.

**Additional context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
Agreed-upon confirmation of the requirements when done can be deemed as complete

**Comment by apuns** [comment] 2022-04-26 00:55
duplicate of #89 & this action was speculative, so closing this ticket

**Closed by apuns** 2022-04-26 00:55 UTC
Labels: CleanBC
